export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const REQUEST_FAIL = 'LOGIN_REQUEST_FAIL';
export const UPDATE_INPUT = 'LOGIN_UPDATE_INPUT';
